### ISSUE TITLE
in2sql

### ISSUE THREAD

**Issue by er77** [rkapl123/DBAddin#9]
hi!

  i think we can work together ))   
 you can get from my project some UI elements  for observing sql tables and create connections 

https://sourceforge.net/projects/in2sql/

**Comment by rkapl123** [comment]
Thanks a lot, your project looks really impressive!
I'll be looking at the sources today.

-regards,
Roland

**Comment by er77** [comment]
erasyuk@gmail.com

**Comment by rkapl123** [comment]
Thank you a lot, however there are two technological difficulties in reusing parts from your project:
1) You've decided to build on VSTO whereas I'm using Excel-DNA for accessing Excel.
2) A less problematic, but still tedious difference: C# vs. VB.net (I'm already regretting having started with VB.NET, mainly this was due to the legacy project, which was written in VB6)
But I'm still considering including the sidebars, that's something to build menus/trees from.

-regards,
Roland
